In [2]:
import numpy as np
c = np.array([[0, -1, 0], [-1, 4, -1], [0, -1, 0]], dtype=np.int8)
carbon = {'C': c, 'mass' : 12, "electronegativity" : 2.55}
h = np.array([[0, -1, 0], [0, 1, 0], [0, 0, 0]], dtype=np.int8)
hydrogen = {'H': h, 'mass' : 1, "electronegativity" : 2.2}
o = np.array([[0, -1, 0], [0, 6, -2], [0, -1, 0]], dtype=np.int8)
oxygen = {'O': o, 'mass' : 16, "electronegativity" : 3.44}
n = np.array([[0, -2, 0], [-1, 3, -1], [-1, 0, 0]], dtype=np.int8)
nitrogen = {'N': n, 'mass' : 14, "electronegativity" : 3.04}
s = np.array([[0, -2, 0], [-1, 8, 0], [-2, -1, 0]], dtype=np.int8)
sulfur = {'S': s, 'mass' : 32, "electronegativity" : 2.58}
p = np.array([[0, -2, 0], [-1, 8, -1], [0, -1, 0]], dtype=np.int8)
phosphorus = {'P': p, 'mass' : 31, "electronegativity" : 2.19}
f = np.array([[0, -1, 0], [0, 7, -1], [0, -1, 0]], dtype=np.int8)

[array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8),
 array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8),
 array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8),
 array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8),
 array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8)]

NameError: name 'bit' is not defined