In [2]:
import numpy as np
import numpy.typing as npt

berserkium = {
    "name": "Berserkium",
    "symbol": "B",
    "color": "red",
    "micro_state_rules": {
        0 : ,
}


class ChemicalAutomata:
    def __init__(self, grid: npt.NDArray[np.int8]):
        self.grid = grid

    def run(self, generations: int):
        for i in range(generations):
            self.grid = self._update(self.grid)

    def _update(self, grid: npt.NDArray[np.int8]) -> npt.NDArray[np.int8]:
        # get indices of all non-zero elements
        indices = np.argwhere(grid == 1)

        # get the surrounding indices
        surrounding_indices = np.array([[x + i, y + j] 
                                        for x, y in indices 
                                        for i in range(-1, 2) 
                                        for j in range(-1, 2) 
                                        if not (i == 0 and j == 0) ])

        # remove the indices that are out of bounds
        surrounding_indices = surrounding_indices[(surrounding_indices[:, 0] >= 0) 
                                                & (surrounding_indices[:, 0] < grid.shape[0])
                                                & (surrounding_indices[:, 1] >= 0) 
                                                & (surrounding_indices[:, 1] < grid.shape[1])]

        # get the unique surrounding indices
        each_indices = np.unique(surrounding_indices, axis=0)

        # set the surrounding indices to 1 if they have 3 neighbours
        grid[indices[:, 0], indices[:, 1]] = [1 if np.sum(np.all(surrounding_indices == i, axis=1)) == 2 else 0
                                            for i in np.unique(indices, axis=0)]
        grid[each_indices[:, 0], each_indices[:, 1]] = [grid[i[0], i[1]] if np.sum(np.all(surrounding_indices == i, axis=1)) != 3 else 1 
                                            for i in each_indices]

        return grid



[array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8),
 array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8),
 array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8),
 array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8),
 array([[ 0, -1,  0],
        [-1,  4, -1],
        [ 0, -1,  0]], dtype=int8)]

NameError: name 'bit' is not defined